--
-- PostgreSQL database dump
--

\restrict 6lIp5UmJdow1xr71z29zs8Jmm7GUbPTfNnQg3gVylpZ9TUrN5tJ0AydyG0R7Cgy

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: exercise_categories; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.exercise_categories (
    category_id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.exercise_categories OWNER TO nutri;

--
-- Name: exercise_categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

CREATE SEQUENCE public.exercise_categories_category_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.exercise_categories_category_id_seq OWNER TO nutri;

--
-- Name: exercise_categories_category_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: nutri
--

ALTER SEQUENCE public.exercise_categories_category_id_seq OWNED BY public.exercise_categories.category_id;


--
-- Name: exercise_subcategories; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.exercise_subcategories (
    subcategory_id integer NOT NULL,
    category_id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.exercise_subcategories OWNER TO nutri;

--
-- Name: exercise_subcategories_subcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

CREATE SEQUENCE public.exercise_subcategories_subcategory_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.exercise_subcategories_subcategory_id_seq OWNER TO nutri;

--
-- Name: exercise_subcategories_subcategory_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: nutri
--

ALTER SEQUENCE public.exercise_subcategories_subcategory_id_seq OWNED BY public.exercise_subcategories.subcategory_id;


--
-- Name: exercise_subcategory_links; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.exercise_subcategory_links (
    exercise_id integer NOT NULL,
    subcategory_id integer NOT NULL
);


ALTER TABLE public.exercise_subcategory_links OWNER TO nutri;

--
-- Name: exercises; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.exercises (
    exercise_id integer NOT NULL,
    exercise_key character varying(100) NOT NULL,
    exercise_type character varying(100) NOT NULL,
    calories_per_kg numeric(5,2) NOT NULL,
    user_id integer,
    category character varying(20) DEFAULT 'strength'::character varying NOT NULL
);


ALTER TABLE public.exercises OWNER TO nutri;

--
-- Name: exercises_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

CREATE SEQUENCE public.exercises_exercise_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.exercises_exercise_id_seq OWNER TO nutri;

--
-- Name: exercises_exercise_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: nutri
--

ALTER SEQUENCE public.exercises_exercise_id_seq OWNED BY public.exercises.exercise_id;


--
-- Name: food; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.food (
    food_id integer NOT NULL,
    description character varying(255) NOT NULL,
    calories numeric(8,2),
    protein numeric(6,2),
    carbs numeric(6,2),
    total_fat numeric(6,2),
    saturated_fat numeric(6,2),
    cholesterol numeric(6,2),
    sodium numeric(6,2),
    sugar numeric(6,2),
    user_id integer
);


ALTER TABLE public.food OWNER TO nutri;

--
-- Name: food_food_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

ALTER TABLE public.food ALTER COLUMN food_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.goals (
    goal_id integer NOT NULL,
    user_id integer NOT NULL,
    goal_type character varying(50) NOT NULL,
    date_added timestamp without time zone DEFAULT now(),
    goal_end_date date,
    goal_complete boolean DEFAULT false
);


ALTER TABLE public.goals OWNER TO nutri;

--
-- Name: goals_goal_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

ALTER TABLE public.goals ALTER COLUMN goal_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goals_goal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meal_foods; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.meal_foods (
    meal_id integer NOT NULL,
    food_id integer NOT NULL,
    food_amount numeric(8,2) NOT NULL
);


ALTER TABLE public.meal_foods OWNER TO nutri;

--
-- Name: meals; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.meals (
    meal_id integer NOT NULL,
    user_id integer NOT NULL,
    meal_date date DEFAULT now(),
    meal_type character varying(50),
    meal_name character varying(255),
    parent_meal_id integer
);


ALTER TABLE public.meals OWNER TO nutri;

--
-- Name: meals_meal_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

ALTER TABLE public.meals ALTER COLUMN meal_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meals_meal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: progress_tracking; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.progress_tracking (
    tracking_id integer NOT NULL,
    user_id integer NOT NULL,
    goal_id integer,
    height numeric(5,2),
    weight numeric(5,2),
    recorded_date timestamp without time zone DEFAULT now()
);


ALTER TABLE public.progress_tracking OWNER TO nutri;

--
-- Name: progress_tracking_tracking_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

ALTER TABLE public.progress_tracking ALTER COLUMN tracking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progress_tracking_tracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    date_of_birth date NOT NULL,
    nickname character varying(100) DEFAULT ''::character varying
);


ALTER TABLE public.users OWNER TO nutri;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_exercises; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.workout_exercises (
    workout_id integer NOT NULL,
    exercise_id integer NOT NULL,
    exercise_duration integer NOT NULL,
    sets integer,
    reps integer,
    weight numeric(5,2),
    distance numeric(7,2),
    incline numeric(3,1),
    max_weight integer
);


ALTER TABLE public.workout_exercises OWNER TO nutri;

--
-- Name: workouts; Type: TABLE; Schema: public; Owner: nutri
--

CREATE TABLE public.workouts (
    workout_id integer NOT NULL,
    user_id integer NOT NULL,
    name character varying(255),
    notes text,
    duration integer NOT NULL,
    workout_date timestamp without time zone DEFAULT now(),
    is_template boolean DEFAULT true NOT NULL,
    total_calories_burned numeric(7,2)
);


ALTER TABLE public.workouts OWNER TO nutri;

--
-- Name: workouts_workout_id_seq; Type: SEQUENCE; Schema: public; Owner: nutri
--

CREATE SEQUENCE public.workouts_workout_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.workouts_workout_id_seq OWNER TO nutri;

--
-- Name: workouts_workout_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: nutri
--

ALTER SEQUENCE public.workouts_workout_id_seq OWNED BY public.workouts.workout_id;


--
-- Name: exercise_categories category_id; Type: DEFAULT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_categories ALTER COLUMN category_id SET DEFAULT nextval('public.exercise_categories_category_id_seq'::regclass);


--
-- Name: exercise_subcategories subcategory_id; Type: DEFAULT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_subcategories ALTER COLUMN subcategory_id SET DEFAULT nextval('public.exercise_subcategories_subcategory_id_seq'::regclass);


--
-- Name: exercises exercise_id; Type: DEFAULT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercises ALTER COLUMN exercise_id SET DEFAULT nextval('public.exercises_exercise_id_seq'::regclass);


--
-- Name: workouts workout_id; Type: DEFAULT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.workouts ALTER COLUMN workout_id SET DEFAULT nextval('public.workouts_workout_id_seq'::regclass);


--
-- Name: exercise_categories exercise_categories_name_key; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_categories
    ADD CONSTRAINT exercise_categories_name_key UNIQUE (name);


--
-- Name: exercise_categories exercise_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_categories
    ADD CONSTRAINT exercise_categories_pkey PRIMARY KEY (category_id);


--
-- Name: exercise_subcategories exercise_subcategories_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_subcategories
    ADD CONSTRAINT exercise_subcategories_pkey PRIMARY KEY (subcategory_id);


--
-- Name: exercise_subcategory_links exercise_subcategory_links_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_subcategory_links
    ADD CONSTRAINT exercise_subcategory_links_pkey PRIMARY KEY (exercise_id, subcategory_id);


--
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (exercise_id);


--
-- Name: food food_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_pkey PRIMARY KEY (food_id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (goal_id);


--
-- Name: meal_foods meal_foods_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.meal_foods
    ADD CONSTRAINT meal_foods_pkey PRIMARY KEY (meal_id, food_id);


--
-- Name: meals meals_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.meals
    ADD CONSTRAINT meals_pkey PRIMARY KEY (meal_id);


--
-- Name: progress_tracking progress_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.progress_tracking
    ADD CONSTRAINT progress_tracking_pkey PRIMARY KEY (tracking_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: workout_exercises workout_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.workout_exercises
    ADD CONSTRAINT workout_exercises_pkey PRIMARY KEY (workout_id, exercise_id);


--
-- Name: workouts workouts_pkey; Type: CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.workouts
    ADD CONSTRAINT workouts_pkey PRIMARY KEY (workout_id);


--
-- Name: exercise_subcategories exercise_subcategories_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_subcategories
    ADD CONSTRAINT exercise_subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.exercise_categories(category_id) ON DELETE CASCADE;


--
-- Name: exercise_subcategory_links exercise_subcategory_links_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_subcategory_links
    ADD CONSTRAINT exercise_subcategory_links_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id) ON DELETE CASCADE;


--
-- Name: exercise_subcategory_links exercise_subcategory_links_subcategory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercise_subcategory_links
    ADD CONSTRAINT exercise_subcategory_links_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.exercise_subcategories(subcategory_id) ON DELETE CASCADE;


--
-- Name: exercises exercises_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: food food_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: goals goals_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: meal_foods meal_foods_food_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.meal_foods
    ADD CONSTRAINT meal_foods_food_id_fkey FOREIGN KEY (food_id) REFERENCES public.food(food_id) ON DELETE CASCADE;


--
-- Name: meal_foods meal_foods_meal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.meal_foods
    ADD CONSTRAINT meal_foods_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(meal_id) ON DELETE CASCADE;


--
-- Name: meals meals_parent_meal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.meals
    ADD CONSTRAINT meals_parent_meal_id_fkey FOREIGN KEY (parent_meal_id) REFERENCES public.meals(meal_id) ON DELETE CASCADE;


--
-- Name: meals meals_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.meals
    ADD CONSTRAINT meals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: progress_tracking progress_tracking_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.progress_tracking
    ADD CONSTRAINT progress_tracking_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(goal_id) ON DELETE SET NULL;


--
-- Name: progress_tracking progress_tracking_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.progress_tracking
    ADD CONSTRAINT progress_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: workout_exercises workout_exercises_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.workout_exercises
    ADD CONSTRAINT workout_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id) ON DELETE CASCADE;


--
-- Name: workout_exercises workout_exercises_workout_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.workout_exercises
    ADD CONSTRAINT workout_exercises_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(workout_id) ON DELETE CASCADE;


--
-- Name: workouts workouts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: nutri
--

ALTER TABLE ONLY public.workouts
    ADD CONSTRAINT workouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 6lIp5UmJdow1xr71z29zs8Jmm7GUbPTfNnQg3gVylpZ9TUrN5tJ0AydyG0R7Cgy

