from flask import Blueprint, request, jsonify, session
import datetime
import bcrypt
from utils.db import get_connection
from utils.check_input import validate_username, validate_dob

#Create blueprint for authenticaion routes
auth = Blueprint("auth", __name__)

#For registering
@auth.route("/register", methods=["POST"])
def register():

    #Get info from request JSON
    data = request.json
    username = data.get("username")
    dob = data.get("dob")
    password = data.get("password")
    
    #Ensure all fields are filled out (All fields are required)
    if not username or not dob or not password:
        return jsonify({"error" : "All fields are requried"}), 400
    
    # Validate username
    is_valid, error = validate_username(username)
    if not is_valid:
        return jsonify({"error": error}), 400
    
    #Validate DOB
    is_valid, error, dob_date = validate_dob(dob)
    if not is_valid:
        return jsonify({"error" : error}), 400
    
    try:
        #connect to DB
        conn = get_connection()
        cur = conn.cursor()
        
        #Check if username already exists
        cur.execute("SELECT 1 FROM users WHERE username = %s", (username,))
        if cur.fetchone():
            cur.close()
            conn.close()
            return jsonify({"error":"username already exists, please pick a new one"}), 400

        #Encrypt password
        encrypt_pw = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
        
        #Insert User into the Database (they are now registered)
        cur.execute(
            "INSERT INTO users (username, password, date_of_birth) VALUES (%s, %s, %s) RETURNING user_id",
            (username, encrypt_pw, dob_date)
        )

        #Get the user_id (automatically generated by DB)
        result = cur.fetchone()
        new_user_id = result[0]

        #Commit and close DB connections
        conn.commit()
        cur.close()
        conn.close()

        #Save the username and user_id into the flask session
        session["user_id"] = new_user_id
        session["username"] = username
        #Session lasts a long time so user can stay logged in (not too worried about security)
        session.permanent = True
        
        return jsonify({"message" : "User registered successfully"}), 201

    except Exception as e:
        print("REGISTER ERROR:", e)   # DEBUG PRINT
        return jsonify({"error": str(e)}), 500

#For logging in
@auth.route("/login", methods=["POST"])
def login():

    #Get info from request json
    data = request.json
    username = data.get("username")
    password = data.get("password")
    
    #Check that the user filled in the username and password (required fields)
    if not username or not password:
        return jsonify({"error" : "Please enter both a username and a password"}), 400
    
    try:
        #Connect to DB
        conn = get_connection()
        cur = conn.cursor()
        
        #Fetch user from DB based on username
        cur.execute("SELECT user_id, password FROM users WHERE username=%s", (username,))
        row = cur.fetchone()
        
        #Ensure user exists
        if not row:
            return jsonify({"error" : "Invalid username"}), 401
        
        #get user_id and password
        user_id, encrypted_pw = row
        
        #Check password using bcrypt
        if not bcrypt.checkpw(password.encode("utf-8"), encrypted_pw.encode("utf-8")):
            cur.close()
            conn.close()
            return jsonify({"error" : "Invalid password"}), 401
        
        #Log the user in and store information in flask session
        session["user_id"] = user_id
        session["username"] = username
        session.permanent = True
        
        #Close connection to DB
        cur.close()
        conn.close()
        return jsonify({"message" : "Successful login"}), 200
    
    except Exception as e:
        print("LOGIN ERROR:", e)
        return jsonify({"error": str(e)}), 500

#Validate User        
@auth.route('/session')
def session_status():
    #get user_id from flask session
    user_id = session.get('user_id')
    if not user_id:
        #Kick user out if not in flask session
        return jsonify({"logged_in" : False})
    
    #Connect to DB fetch user and disconnect
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("SELECT user_id, username FROM users WHERE user_id = %s", (user_id,))
    user = cur.fetchone()
    cur.close()
    conn.close()
    
    #If the user exists return info in JSON
    if user:
        return jsonify({
            "logged_in" : True,
            "user_id" : user[0],
            "username" : user[1]
        })
    else: #Return error Kick user out
        return jsonify({"Logged_in" : False}) 

#For logging out
@auth.route("/logout", methods=["POST"])
def logout():
    #Logs user out by clearing their flask session
    session.clear()
    return jsonify({"message": "Logged out successfully"}), 200
